verbose

diff --git a/.github/workflows/cd-test-deploy.yaml b/.github/workflows/cd-test-deploy.yaml
--- a/.github/workflows/cd-test-deploy.yaml
+++ b/.github/workflows/cd-test-deploy.yaml
@@ -35,26 +35,26 @@ jobs:
      - name: deploy taged updates
        run: |
          ssh  -o StrictHostKeyChecking=no ubuntu@${{ secrets.TEST_VM_IP }} << 'EOF'
-           set -e
+           set -e -v
            export GIT_SSH_COMMAND="ssh -i /home/ubuntu/.ssh/aio_machine_user_key -o StrictHostKeyChecking=no "
-           sudo systemctl stop rc2_test || true
+           sudo systemctl stop rc2_test || echo "stop failed" || true
            timestamp=$(date -Iseconds)
            echo "$timestamp ref=${{ github.ref }} ref_name=${{ github.ref_name }}" >> CD_test_action.log
            cd RC2-hub
-           git fetch -p -P
+           git fetch -p -P || print "Failed with: %d" $? || true
            ref="${{github.ref}}"
            if [[ $ref == "refs/tags"* ]] ; then
-            git checkout ${{ github.ref_name }} 
+            git checkout ${{ github.ref_name }}  || print "Failed with: %d" $? || true
            fi
            if [[ $ref == "refs/heads"* ]] ; then
-            git checkout refs/remotes/origin/${{ github.ref_name }}
+            git checkout refs/remotes/origin/${{ github.ref_name }} || print "Failed with: %d" $? || true
            fi
            printf "Cleaning is requested: %s" ${{inputs.clean_before_start}}
 
            if [[ "${{ inputs.clean_before_start }}" == "true" ]]; then
             echo "Some cleaning is requested"
            fi
-           sudo systemctl start rc2_test
+           sudo systemctl start rc2_test || print "Failed with: %d" $? || true
          EOF
      - name: kill tunnel
        run: |
